export const MOCK_RECORDS = [
  {
    id: 1,
    title: "The Future of Web Development: Next.js 16 and Beyond",
    category: "Technology",
    readingTime: "6 min read",
    thumbnail: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=60",
    tags: ["#Nextjs", "#React", "#WebDev", "#SSR"],
    authorName: "Alex Rivera",
    authorRole: "Lead Frontend Engineer",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    description: "Explore the cutting-edge features of Next.js 16, React Compiler engine tracking, Server Actions, and rendering architectures.",
    body: "Next.js 16 introduces foundational shifts in how modern developers reason about serialization boundaries and network data flow layouts. By natively leveraging the production-ready React Compiler layer, the framework eliminates standard boilerplate overhead, providing automatic component memoization.\n\nThis architecture shift directly improves runtime metric evaluations by optimizing the reconciliation loop. Combined with progressive streaming hydration pipelines, layout components load without triggering unoptimized thread blocking scripts."
  },
  {
    id: 2,
    title: "Mastering Distributed State Controls in Highly Scalable Systems",
    category: "Architecture",
    readingTime: "9 min read",
    thumbnail: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&auto=format&fit=crop&q=60",
    tags: ["#Scale", "#Systems", "#Cloud", "#Distributed"],
    authorName: "Sarah Chen",
    authorRole: "Principal Systems Architect",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    description: "An architectural analysis of micro-frontend event streams, structural state controls, and high-performance networks.",
    body: "Managing systemic data state across asynchronous multi-region availability zones presents fundamental coordination trade-offs. This breakdown dives directly into event-driven pub/sub topographies, comparing sequential consistency invariants with transactional state validation loops at the edge interface level.\n\nThrough rigorous benchmark tracking, we demonstrate that isolating configuration changes within granular logical boundary clusters protects systems against downstream cascade failures."
  },
  {
    id: 3,
    title: "Securing Production Pipelines: Zero-Trust Engineering Workflows",
    category: "Security",
    readingTime: "7 min read",
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=60",
    tags: ["#Cyber", "#Security", "#Auth", "#DevOps"],
    authorName: "Marcus Vance",
    authorRole: "Head of DevSecOps",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    description: "How modern cloud operations groups build resilient cryptographic handshakes and isolation layers safely.",
    body: "The traditional perimeter defense model is no longer sufficient to secure modern distributed continuous deployment environments. A resilient deployment workflow treats every micro-agent, internal system call, and automation hook as completely untrusted until explicitly verified.\n\nBy executing zero-knowledge validation steps across code artifact handshakes, teams can completely immunize their build pipelines against malicious supply-chain injections."
  },
  {
    id: 4,
    title: "Optimizing Database Layout Operations for Sub-Millisecond Queries",
    category: "Database",
    readingTime: "5 min read",
    thumbnail: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop&q=60",
    tags: ["#SQL", "#Performance", "#Data", "#Indexing"],
    authorName: "Elena Rostova",
    authorRole: "Staff Database Engineer",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    description: "Practical strategies for indexing relational structures and handling heavy transactional operations under heavy load.",
    body: "Slow response times in heavily concurrent database workloads are typically tied directly to unoptimized index layouts and page allocation locks. This publication breaks down the mechanical disk operations governing indexing structures under heavy data manipulation queries.\n\nWe present concrete layout strategies for optimizing data arrangement, reducing memory requirements, and leveraging localized storage layout caches. These engineering principles minimize scanning overhead seamlessly."
  },
  {
    id: 5,
    title: "Designing Event-Driven Microservices with Apache Kafka",
    category: "Architecture",
    readingTime: "8 min read",
    thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=60",
    tags: ["#Kafka", "#EventDriven", "#Backend"],
    authorName: "Liam O'Connor",
    authorRole: "Principal Engineer",
    authorAvatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80",
    description: "A comprehensive guide to message replication, partition sizing strategies, and consumer group rebalancing patterns.",
    body: "Apache Kafka acts as the neurological spinal cord for decoupled data ecosystems operating under massive scales. Setting up stable consumer clusters requires careful configuration of commit intervals and thread management paths.\n\nThis system writeup details strategies for structuring message key distribution arrays, optimizing data serialization overheads, and gracefully preventing cascade lockouts when consumer brokers drop offline under load streams."
  },
  {
    id: 6,
    title: "Building Resilient UI Foundations with CSS Container Queries",
    category: "Technology",
    readingTime: "4 min read",
    thumbnail: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&auto=format&fit=crop&q=60",
    tags: ["#CSS", "#Frontend", "#DesignSystems"],
    authorName: "Aria Montgomery",
    authorRole: "Senior UI Architect",
    authorAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    description: "Move past media queries. Discover component-driven responsive layouts that style perfectly across varying layout spaces.",
    body: "Container queries mark a significant evolution in frontend engineering design paradigms, detaching viewport dependencies from fluid style injection matrices.\n\nBy framing layout calculations relative to immediate inline wrapper targets, layout components dynamically morph their typography scales, padding values, and element inline flow rules without invoking rigid macro-viewport boundaries."
  },
  {
    id: 7,
    title: "GraphQL vs REST: Edge Performance Metrics and Data Fetching Cost",
    category: "Technology",
    readingTime: "6 min read",
    thumbnail: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop&q=60",
    tags: ["#GraphQL", "#API", "#Networking"],
    authorName: "Devon Brooks",
    authorRole: "API Framework Lead",
    authorAvatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    description: "An empirical analysis of over-fetching penalties, parser latency overhead, and gateway aggregation paradigms.",
    body: "Selecting an interaction interface specification heavily modifies response payloads and caching capability matrices across remote nodes. While GraphQL minimizes client network round-trips via unified schema endpoints, it introduces computing strains during runtime validation fields.\n\nThis breakdown documents parsing bottlenecks observed under nested resource arrays and provides optimization metrics for caching GraphQL responses cleanly."
  },
  {
    id: 8,
    title: "A Practical Guide to Structuring Infrastructure as Code with Terraform",
    category: "DevOps",
    readingTime: "11 min read",
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=60",
    tags: ["#Terraform", "#IaC", "#AWS"],
    authorName: "Jordan Vance",
    authorRole: "Cloud Platform Lead",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    description: "Isolate environments safely. Learn state locking patterns, module abstractions, and pipeline security structures.",
    body: "Provisioning critical datacenter blueprints through declarative configuration files mandates strict state enforcement routines. Utilizing isolated block-storage backends prevent merge clashes across decoupled orchestration infrastructure engines.\n\nWe provide real-world pipeline definitions mapping immutable deployment targets across sandbox networks, staging layers, and live production endpoints safely."
  },
  {
    id: 9,
    title: "Deep Dive into WebAssembly: Running Native Code in the Browser",
    category: "Technology",
    readingTime: "8 min read",
    thumbnail: "https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=800&auto=format&fit=crop&q=60",
    tags: ["#Wasm", "#Rust", "#Performance"],
    authorName: "Nikolai Volkov",
    authorRole: "Compiler Research Lead",
    authorAvatar: "https://images.unsplash.com/photo-1489980508314-941910ded1f4?w=150&auto=format&fit=crop&q=80",
    description: "Accelerate dense arithmetic tasks. Learn linear memory structures, function table bindings, and Rust setups.",
    body: "WebAssembly unlocks computational efficiencies inside standard client contexts that were previously unattainable via standard runtime parsing paths. By translating lower-level source artifacts into compressed binary instructions, the system processes multi-threaded workloads seamlessly.\n\nThis investigation explores shared-memory array structures and provides implementation metrics tracking video transcoding workloads executed natively within the user interface."
  },
  {
    id: 10,
    title: "Managing Big Data: Scaling Distributed Queries with Presto",
    category: "Database",
    readingTime: "10 min read",
    thumbnail: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop&q=60",
    tags: ["#Presto", "#BigData", "#Analytics"],
    authorName: "Elena Rostova",
    authorRole: "Staff Database Engineer",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    description: "Execute interactive ad-hoc queries across multi-petabyte analytics storage systems cleanly.",
    body: "Querying unstructured data clusters requires query engines capable of decoupling storage retrieval layers from immediate calculation tasks. Presto solves this through pipelined execution structures.\n\nBy tuning worker node allocation states and sorting query tracking heuristics, database engineers can aggressively compress multi-hour execution runs into predictable, interactive sub-second windows."
  },
  {
    id: 11,
    title: "Automating Canary Deployments with Kubernetes and Istio Service Mesh",
    category: "DevOps",
    readingTime: "9 min read",
    thumbnail: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=800&auto=format&fit=crop&q=60",
    tags: ["#K8s", "#Istio", "#CI-CD"],
    authorName: "Marcus Vance",
    authorRole: "Head of DevSecOps",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    description: "Shift traffic progressively. Monitor telemetry patterns, error rate responses, and automated safe rollback loops.",
    body: "Releasing software patches without impacting running systems requires precision traffic mirroring models. Istio intercepts logical proxy handshakes across micro-frontend boundaries to route target subsets cleanly.\n\nThis article outlines specific VirtualService configuration declarations that automate incremental rollout increments, terminating faulty service updates instantly when metric exceptions exceed specified safety levels."
  },
  {
    id: 12,
    title: "Mastering TypeScript: Advanced Mapping Types and Conditional Structures",
    category: "Technology",
    readingTime: "5 min read",
    thumbnail: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop&q=60",
    tags: ["#TypeScript", "#Coding", "#Advanced"],
    authorName: "Alex Rivera",
    authorRole: "Lead Frontend Engineer",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    description: "Enforce strict interface safety across dynamic application frameworks via utility mapping functions.",
    body: "Basic typing definitions often collapse when writing polymorphic components meant to process varying dictionary inputs. TypeScript's conditional type keywords enable precise programmatic signature verification.\n\nWe provide complex examples building strictly guarded schema systems that prevent compile-time drift, ensuring interface elements receive reliable data properties across expansive application frameworks."
  },
  {
    id: 13,
    title: "Securing APIs against OWASP Top 10 Anomalies: Production Defense",
    category: "Security",
    readingTime: "7 min read",
    thumbnail: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format&fit=crop&q=60",
    tags: ["#OWASP", "#AppSec", "#PenTesting"],
    authorName: "Marcus Vance",
    authorRole: "Head of DevSecOps",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    description: "Mitigate broken object authorization, injection strings, and bad rate configurations natively.",
    body: "Exploiting input validation fields represents the primary entry vector for bad actors tracking application infrastructure endpoints. Relying on perimeter validation structures leaves downstream databases highly exposed.\n\nThis technical log outlines middleware patterns for implementing strict content security policies, parameter sanitization filters, and rate-limiting rules directly inside code execution paths."
  },
  {
    id: 14,
    title: "The Architecture of Modern Search Engines: Inverted Index Mechanics",
    category: "Architecture",
    readingTime: "8 min read",
    thumbnail: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&auto=format&fit=crop&q=60",
    tags: ["#Search", "#Algorithms", "#Lucene"],
    authorName: "Sarah Chen",
    authorRole: "Principal Systems Architect",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    description: "How document parsing, tokenizer streams, and positional vector storage accelerate search lookups.",
    body: "Processing search requests across expansive textual archives mandates highly specialized indexing formats. Inverted indexes organize raw string text sequences into discrete term matrices mapped directly to target resource addresses.\n\nThis deep dive builds a miniature text analyzer loop, tracing text processing operations, word stem conversions, and vector matrix matches that return relevant results."
  },
  {
    id: 15,
    title: "Optimizing Client Assets: Next-Gen Image Compression Workflows",
    category: "Technology",
    readingTime: "5 min read",
    thumbnail: "https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=800&auto=format&fit=crop&q=60",
    tags: ["#WebPerformance", "#AVIF", "#Frontend"],
    authorName: "Aria Montgomery",
    authorRole: "Senior UI Architect",
    authorAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    description: "Reduce bundle overhead. Setup automated build-time pipelines utilizing modern format encoding wrappers.",
    body: "Heavy imagery assets represent the single largest contributor to core web vital metric failures across client apps. Transitioning assets to modern image formats reduces weight requirements significantly.\n\nThis writeup evaluates compression performance, presenting automated scripting pipelines that optimize resource rendering without introducing visible clarity regressions."
  },
  {
    id: 16,
    title: "Redis Sharding Patterns: Handling High Concurrency Memory Topographies",
    category: "Database",
    readingTime: "6 min read",
    thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=60",
    tags: ["#Redis", "#Caching", "#SystemDesign"],
    authorName: "Elena Rostova",
    authorRole: "Staff Database Engineer",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    description: "Distribute lookup strain. Implement hash slot routing structures to scale memory lookup arrays.",
    body: "Single-instance memory storage engines inevitably hit hard boundaries when concurrent connection loops surge into massive millions. Redis clusters handle this through automated sharding operations over distributed address spaces.\n\nThis breakdown documents slot partitioning rules, failover mechanisms under cluster node loss, and cross-slot multi-key request execution paths."
  },
  {
    id: 17,
    title: "Micro-Frontends Orchestration: Dynamic Module Federation Systems",
    category: "Architecture",
    readingTime: "9 min read",
    thumbnail: "https://images.unsplash.com/photo-1614741118887-7a4ee193a5fa?w=800&auto=format&fit=crop&q=60",
    tags: ["#Webpack", "#MicroFrontends", "#Architecture"],
    authorName: "Alex Rivera",
    authorRole: "Lead Frontend Engineer",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    description: "Decouple massive development organizations by sharing standalone UI code directly at runtime.",
    body: "Monolithic client projects inevitably complicate shipping cycles as engineering teams expand. Module Federation enables systems to share sub-application builds dynamically on production web spaces.\n\nWe analyze asset loading workflows, error handling interfaces when standalone builds crash, and context isolation patterns used to keep shared runtimes safe."
  },
  {
    id: 18,
    title: "Building Real-Time Interfaces: WebSocket Scaling at the Gateway Layer",
    category: "Technology",
    readingTime: "7 min read",
    thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=60",
    tags: ["#WebSockets", "#RealTime", "#Networking"],
    authorName: "Liam O'Connor",
    authorRole: "Principal Engineer",
    authorAvatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80",
    description: "Handle millions of concurrent connections through specialized proxy adjustments and connection tracking layers.",
    body: "Persistent bidirectional socket states quickly consume operating system file descriptors if memory allocations aren't rigorously optimized. Managing this at the edge requires specific proxy configurations.\n\nThis engineering blueprint details kernel parameter adjustments, fallback protocols when proxies lose connectivity, and pub/sub message synchronization across separate proxy nodes."
  },
  {
    id: 19,
    title: "Eliminating Memory Leaks in React Applications: Profiling Workflows",
    category: "Technology",
    readingTime: "5 min read",
    thumbnail: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&auto=format&fit=crop&q=60",
    tags: ["#React", "#Debugging", "#JavaScript"],
    authorName: "Aria Montgomery",
    authorRole: "Senior UI Architect",
    authorAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    description: "Master browser development tools to locate and fix broken garbage collection hooks inside complex applications.",
    body: "Unreleased closure references and orphaned window event listeners continuously degrade performance if left unmanaged inside long-lived single-page layouts.\n\nThis article outlines systematic performance recording paths, detailing how to track memory growth anomalies and correctly destroy reference paths inside component lifecycles."
  },
  {
    id: 20,
    title: "Continuous Database Migrations: Zero-Downtime Schema Strategies",
    category: "Database",
    readingTime: "8 min read",
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=60",
    tags: ["#DevOps", "#Databases", "#Migrations"],
    authorName: "Elena Rostova",
    authorRole: "Staff Database Engineer",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    description: "Modify underlying database tables safely while processing millions of active user transactional queries.",
    body: "Altering foundational table definitions under heavy production usage loops can trigger locked states that stall system workflows. Managing this safely requires multi-stage deployment patterns.\n\nThis system writeup charts the expand-and-contract structural strategy, showing how to introduce columns, synchronize writing pipelines, and safely remove old data fields without dropping queries."
  },
  {
    id: 21,
    title: "Advanced Docker Security: Hardening Container Isolation Formations",
    category: "Security",
    readingTime: "7 min read",
    thumbnail: "https://images.unsplash.com/photo-1605810230434-7631ac76ec81?w=800&auto=format&fit=crop&q=60",
    tags: ["#Docker", "#Security", "#Containers"],
    authorName: "Marcus Vance",
    authorRole: "Head of DevSecOps",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    description: "Prevent sandbox escapes. Enforce read-only file systems, drop root access, and use system filter layers.",
    body: "Default container installations often share kernel resource privileges that open security vectors if application runtimes are breached. Restricting container runtime permissions mitigates down-stream server takeover risks.\n\nWe provide complete configurations setting up non-privileged execution contexts, immutable file footprints, and strict resource capability limitations."
  },
  {
    id: 22,
    title: "Graph Database Paradigms: Transitioning to Neo4j Systems",
    category: "Database",
    readingTime: "6 min read",
    thumbnail: "https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&auto=format&fit=crop&q=60",
    tags: ["#Neo4j", "#GraphDB", "#NoSQL"],
    authorName: "Sarah Chen",
    authorRole: "Principal Systems Architect",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    description: "Model interconnected identity relationships smoothly without building slow multi-join query setups.",
    body: "Relational database models struggle significantly when executing deep recursive lookups across dense connection chains. Graph databases treat relationships as physical records, eliminating translation overhead.\n\nThis guide breaks down graph query syntax structures, indexing patterns, and performance differences noted when processing complex relationship paths at scale."
  },
  {
    id: 23,
    title: "Edge Computing Paradigms: Moving Logic to Cloudflare Workers",
    category: "Architecture",
    readingTime: "6 min read",
    thumbnail: "https://images.unsplash.com/photo-1526253038957-bce54e05968e?w=800&auto=format&fit=crop&q=60",
    tags: ["#Edge", "#Serverless", "#Cloudflare"],
    authorName: "Jordan Vance",
    authorRole: "Cloud Platform Lead",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    description: "Minimize user round-trip times by executing serverless functional logic closer to the user connection node.",
    body: "Centralized server hubs present unavoidable network latency bottlenecks for global user bases. Running serverless scripts inside lightweight execution boundaries across distributed edge networks answers this challenge.\n\nThis analysis details request routing control, fast edge data storage strategies, and deployment routines that reduce time-to-first-byte parameters globally."
  },
  {
    id: 24,
    title: "Building Accessible UI Components: Accessible Focus Ring Controls",
    category: "Technology",
    readingTime: "4 min read",
    thumbnail: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&auto=format&fit=crop&q=60",
    tags: ["#A11y", "#Tailwind", "#WebDev"],
    authorName: "Aria Montgomery",
    authorRole: "Senior UI Architect",
    authorAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    description: "Ensure full compliance with accessibility guidelines without disrupting branding and styling themes.",
    body: "Hiding native interaction rings for purely aesthetic reasons isolates keyboard users and fails accessibility compliance reviews. Designing explicit component styles solves this user experience friction point.\n\nWe document implementation patterns utilizing modern state selectors that surface visibility rings exclusively when navigating via input hardware, keeping layouts clean and usable."
  }
];